services:
  web:
    image: dgudovic/nginx:1.0
    ports:
      - "80:80"
  app:
    image: dgudovic/php-composer:1.1
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
  cache:
    image: redis:latest
volumes:
  mysqldata: