services:
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  mysqldata: