name: TranslateThis

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Composer Dependencies
        working-directory: ./app
        run: composer install --prefer-dist

      - name: Run Tests
        working-directory: ./app
        run: composer run-phpunit

      - run: docker build --target app -t dgudovic/php-composer:1.1 -f ./php/Dockerfile .
      - run: docker build -t dgudovic/nginx:1.0 -f ./nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push dgudovic/php-composer:1.1
      - run: docker push dgudovic/nginx:1.0